plots:
    - mispredicted
    - loss:
        y:
          dvclive/plots/metrics/train/loss.tsv: loss
          dvclive/plots/metrics/eval/loss.tsv: loss
    - accuracy:
        y:
          dvclive/plots/metrics/train/accuracy.tsv: accuracy
          dvclive/plots/metrics/eval/accuracy.tsv: accuracy
metrics:
    - dvclive/metrics.json
params:
    - params.yaml
stages:
  train:
    cmd: 
    - python train.py data/
    deps:
    - data/
    - train.py
    - requirements.txt
    - params.yaml
    outs:
    - model
    - dvclive:
        cache: false
  inference:
    cmd: python inference.py data/
    deps:
    - data
    - model
    - inference.py
    outs:
    - predictions
    - mispredicted
